// DrmExt.idl : IDL source for DrmExt
//

// This file will be processed by the MIDL tool to
// produce the type library (DrmExt.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	object,
	uuid(5434D5CB-587F-427A-AEB5-02D31466B512),
	helpstring("IDrmShlExt Interface"),
	pointer_default(unique)
]
interface IDrmShlExt : IUnknown{
};
[
	uuid(07BF1E56-83B5-4A7F-ADFA-202C9F8DDBF9),
	version(1.0),
	helpstring("DrmExt 1.0 Type Library")
]
library DrmExtLib
{
	importlib("stdole2.tlb");
	[
		uuid(4650B2E6-1F31-4515-9A85-558B245611B3),
		helpstring("DrmShlExt Class")
	]
	coclass DrmShlExt
	{
		[default] interface IDrmShlExt;
	};
};
