// DrmExt.idl : IDL source for DrmExt
//

// This file will be processed by the MIDL tool to
// produce the type library (DrmExt.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	object,
	uuid(5AD4DD46-7126-4A6C-9CAF-DE110F04E8D3),
	helpstring("IDrmShlExt Interface"),
	pointer_default(unique)
]
interface IDrmShlExt : IUnknown{
};
[
	uuid(23420D46-BCA2-4BBB-B620-E930611EB716),
	version(1.0),
	helpstring("DrmExt 1.0 Type Library")
]
library DrmExtLib
{
	importlib("stdole2.tlb");
	[
		uuid(EDC76DD8-5EC8-4C7C-8C12-56F0EDBB5B4D),
		helpstring("DrmShlExt Class")
	]
	coclass DrmShlExt
	{
		[default] interface IDrmShlExt;
	};
};
